import streamlit as st
from groq import Groq
import json
import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import pypdf
import io

# Page Configuration
st.set_page_config(page_title="I Present - AI Presentation Designer", layout="wide", page_icon="📊")

st.title("📊 I Present")
st.subheader("Generate Custom PPTX, Speaker Notes & Q&A using AI")

# Sidebar for API Key & Configuration
st.sidebar.header("🔑 Configuration")
api_key_input = st.sidebar.text_input("Enter your Groq API Key:", type="password")

# Use sidebar API key or Environment Variable
api_key = api_key_input or os.environ.get("GROQ_API_KEY")

if not api_key:
    st.info("💡 Please enter your Groq API Key in the sidebar or set it as an environment variable to proceed.")

# Helper function to extract text from PDF
def extract_text_from_pdf(pdf_file):
    reader = pypdf.PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text

# Helper function to create PPTX file from AI structured JSON
def create_pptx(slides_data, presentation_title):
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = presentation_title
    subtitle.text = "Generated by I Present"

    # 2. Content Slides
    blank_slide_layout = prs.slide_layouts[6]
    
    for slide_info in slides_data:
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # Add Slide Title
        txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(8.4), Inches(1))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = slide_info.get("slide_title", "Untitled Slide")
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = RGBColor(24, 43, 73)
        
        # Add Bullet Points
        txBox_content = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(8.4), Inches(5))
        tf_content = txBox_content.text_frame
        tf_content.word_wrap = True
        
        bullets = slide_info.get("bullet_points", [])
        for i, point in enumerate(bullets):
            p = tf_content.add_paragraph() if i > 0 else tf_content.paragraphs[0]
            p.text = point
            p.font.size = Pt(18)
            p.space_after = Pt(12)

    # Save presentation to memory buffer
    binary_output = io.BytesIO()
    prs.save(binary_output)
    binary_output.seek(0)
    return binary_output

# Main Application UI Form
st.header("1. Input Sources & Preferences")

input_type = st.radio("Choose Input Method:", ["Topic Name", "Upload PDF Document"], horizontal=True)

topic_or_context = ""
if input_type == "Topic Name":
    topic_or_context = st.text_input("Enter Topic Name:", placeholder="e.g., The Future of Renewable Energy")
else:
    uploaded_file = st.file_uploader("Upload PDF File", type=["pdf"])
    if uploaded_file is not None:
        with st.spinner("Extracting text from PDF..."):
            topic_or_context = extract_text_from_pdf(uploaded_file)
            st.success(f"PDF processed successfully! Extracted {len(topic_or_context.split())} words.")

col1, col2 = st.columns(2)
with col1:
    num_slides = st.number_input("Number of Slides:", min_value=3, max_value=20, value=5)
with col2:
    tone_option = st.selectbox("Presentation Tone:", ["Professional", "Formal", "Persuasive", "Educational", "Casual", "Custom"])

if tone_option == "Custom":
    tone = st.text_input("Specify Custom Tone:", value="Creative and Energetic")
else:
    tone = tone_option

extra_instructions = st.text_area("Extra Instructions / Specific Explanations:", placeholder="e.g., Focus heavily on economic impacts, include relevant statistics, etc.")

generate_button = st.button("🚀 Generate Presentation", type="primary")

# Generation Logic
if generate_button:
    if not api_key:
        st.error("Please provide a Groq API Key to proceed.")
    elif not topic_or_context.strip():
        st.error("Please enter a topic or upload a valid PDF file.")
    else:
        with st.spinner("Analyzing content and designing presentation with AI..."):
            try:
                client = Groq(api_key=api_key)
                
                # System Prompt enforcing JSON format
                prompt = f"""
                You are an expert presentation designer and content creator.
                Generate a presentation based on the following details:
                
                Content/Topic Source: {topic_or_context[:6000]}
                Target Number of Slides: {num_slides}
                Tone: {tone}
                Extra Instructions: {extra_instructions}
                
                You MUST respond strictly in valid JSON format with the following structure:
                {{
                    "presentation_title": "Title of Presentation",
                    "slides": [
                        {{
                            "slide_number": 1,
                            "slide_title": "Slide Title Here",
                            "bullet_points": [
                                "Point 1",
                                "Point 2",
                                "Point 3"
                            ]
                        }}
                    ],
                    "short_speaker_notes": [
                        "Slide 1 Notes: ...",
                        "Slide 2 Notes: ..."
                    ],
                    "q_and_a": [
                        {{
                            "question": "Possible audience question 1?",
                            "answer": "Clear concise answer."
                        }}
                    ]
                }}
                Do not include markdown code block wrappers like ```json. Output ONLY raw JSON text.
                """

                # Query Groq API
                chat_completion = client.chat.completions.create(
                    messages=[
                        {"role": "user", "content": prompt}
                    ],
                    model="llama-3.3-70b-versatile",
                    temperature=0.7
                )
                
                raw_response = chat_completion.choices[0].message.content.strip()
                
                # Clean code blocks if present
                if raw_response.startswith("```json"):
                    raw_response = raw_response[7:]
                if raw_response.endswith("```"):
                    raw_response = raw_response[:-3]
                raw_response = raw_response.strip()

                data = json.loads(raw_response)
                
                # Store output in session state
                st.session_state['generated_data'] = data
                st.session_state['pptx_file'] = create_pptx(data.get("slides", []), data.get("presentation_title", "Presentation"))
                st.success("✨ Presentation Generated Successfully!")
                
            except Exception as e:
                st.error(f"Error generating presentation: {str(e)}")

# Display Outputs if generated
if 'generated_data' in st.session_state:
    data = st.session_state['generated_data']
    pptx_file = st.session_state['pptx_file']
    
    st.divider()
    st.header("2. Generated Presentation Package")
    
    # Download Button
    st.download_button(
        label="📥 Download Presentation (.pptx)",
        data=pptx_file,
        file_name=f"{data.get('presentation_title', 'presentation').lower().replace(' ', '_')}.pptx",
        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
    )
    
    tab1, tab2, tab3 = st.tabs(["🖼️ Slides Preview", "📝 Speaker Notes", "❓ Audience Q&A"])
    
    with tab1:
        st.subheader(data.get("presentation_title", "Presentation"))
        for slide in data.get("slides", []):
            with st.expander(f"Slide {slide.get('slide_number', '')}: {slide.get('slide_title', '')}"):
                for point in slide.get("bullet_points", []):
                    st.write(f"• {point}")
                    
    with tab2:
        st.subheader("Short Notes for Presentation Preparation")
        for note in data.get("short_speaker_notes", []):
            st.info(note)
            
    with tab3:
        st.subheader("Anticipated Questions & Answers")
        for idx, qa in enumerate(data.get("q_and_a", []), 1):
            st.markdown(f"**Q{idx}: {qa.get('question')}**")
            st.write(f"**A:** {qa.get('answer')}")
            st.write("---")
